config/routes.rb
Rails.application.routes.draw do
  resources :songs do
    collection do
      get 'search'
    end
  end
  root "songs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ActiveHash::Base
  self.data = [
      {id: 1, name: "Poppin'Party"}, {id: 2, name: "Afterglow"},
      {id: 3, name: "Pastel＊Palettes"}, {id: 4, name: "Roselia"},
      {id: 5, name: "ハロー、ハッピーワールド！"}, {id: 6, name: "RAISE A SUILEN"},
      {id: 7, name: "Morfonica"},{id: 8, name: "その他"}
  ]
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
      {id: 1, name: "オリジナル"}, {id: 2, name: "カバー"}
  ]
end

app/models/song.rb
class Song < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :band
  belongs_to_active_hash :category

end

app/models/style.rb
class Style < ActiveHash::Base
  self.data = [
      {id: 1, name: "オリジナル"}, {id: 2, name: "カバー"}
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @bands = Band.all
    @original = Song.where(category_id: 1)
    @cover = Song.where(category_id: 2)
  end

  def show
    @song = Song.find(params[:id])
  end
  def search
    @bands = Band.all
    @categorys = Category.all
    select_band_array if params[:band].present?
    select_expert_array if params[:expert].present?
    select_category_array if params[:category].present?
    @songs = Song.all
    @songs = @search_band.sort if @search_band.present?
    @songs = @search_expert.sort if @search_expert.present?
    @songs = @search_category.sort if @search_category.present?

    @songs = (@search_band & @search_category).sort if @search_band.present? && @search_category.present?
    @songs = (@search_band & @search_expert).sort if @search_band.present? && @search_expert.present?
    @songs = (@search_expert & @search_category).sort if @search_expert.present? && @search_category.present?

    @songs = (@search_band & @search_expert & @search_category).sort if @search_band.present? && @search_expert.present? && @search_category.present?
  end

  private

  def select_band_array
    @split_band = params[:band]
    @search_band =[]
    @split_band.each do |band|
      @search_band += Song.where('band_id LIKE(?)', "%#{band}%")
    end
  end

  def select_expert_array
    @split_expert = params[:expert]
    @search_expert =[]
    @split_expert.each do |expert|
      @search_expert += Song.where('expert LIKE(?)', "%#{expert}%")
    end
  end

  def select_category_array
    @split_category = params[:category]
    @search_category = Song.where('category_id LIKE(?)', "%#{params[:category]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BangDreamSongSelection
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/songs/index.html.haml
.top
  .top__title
    スマホゲーム『バンドリ！ガールズバンドパーティ！』における
    フリーライブの選曲をサポートするアプリです！
  .top__message
    皆さんは、楽曲選びに困ったことはありませんか？
    %br
    次何やろう？と悩み、長々と楽曲一覧をスクロールした経験があるのではないですか？
    %br
    %h3 そんなあなたのために条件に合わせて自動で選曲します！
    %br
    .top__message--info
      %h2 まずは絞り込み検索してください
      %p ※チェックをしない場合はすべて選択になります
  .form
    = form_with(url: search_songs_path, local: true, method: :get) do |f|
      .form-box
        .form-box__title
          バンド
        .form-box__list
          = f.collection_check_boxes :band, Band.all, :id, :name, include_hidden: false do |b|
            .check_box
              = b.check_box
              = b.label
      .form-box
        .form-box__title
          難易度
        .form-box__level
          EXPERT
        .form-box__list
          = f.collection_check_boxes :expert, Song.group(:expert), :expert, :expert, include_hidden: false do |b|
            .check_box
              = b.check_box
              = b.label

      .form-box
        .form-box__title
          カテゴリ
        = f.collection_select :category, Category.all, :id, :name, prompt:"すべて"
      .action
        :javascript
          function koshin(){
            location.reload();
          }
        %input{onclick: "koshin()", type: "button", value: "更新", class: "render"}/

        = f.submit "決定", class: "submit"

app/views/songs/search.html.haml
.search
  .search__box
    %h1 ＜絞り込み内容＞
    .search__box__list
      .search__box__list--title
        バンド
      .search__box__list--value
        - if @split_band.present?
          - @split_band.each do |n|
            = @bands.find(n).name
        -else
          全バンド

    .search__box__list
      .search__box__list--title
        難易度
      .search__box__list--value
        - if @split_expert.present?
          EXPERT
          - @split_expert.each do |n|
            = n
        - else
          指定なし

    .search__box__list
      .search__box__list--title
        カテゴリ
      .search__box__list--value
        - if @split_category.present?
          = @categorys.find(@split_category).name
        - else
          すべて
    = link_to  "更新", root_path, class: "search__box-back"
  - if @songs.present?
    .search__songs
      %h1 ＜ランダム1曲＞
      :javascript
        function koshin(){
          location.reload();
        }
      %input{onclick: "koshin()", type: "button", value: "更新", class:"search__songs-random"}/

      - song = @songs.sample
      %table{border: "1", class: "table"}
        %tr
          %th
          %th 曲名
          %th バンド名
          %th EASY
          %th NORMAL
          %th HARD
          %th EXPERT
          %th SPECIAL
          %th 配信日
          %th カテゴリ
        %tr
          %td{class: "band#{song.band_id}"}
          %td
            = link_to "#{song.title}", song_path("#{song.id}"), class: "table-title"
          %td.table-band{class: "#{song.band.name}"} #{song.band.name}
          %td.table-level.easy #{song.easy}
          %td.table-level.normal #{song.normal}
          %td.table-level.hard #{song.hard}
          %td.table-level.expert #{song.expert}
          %td.table-level.special #{song.special}
          %td.table-delivery #{song.delivery}
          %td.table-category{class: "category#{song.category_id}"} #{song.category.name}
    .search__songs
      %h1 ＜楽曲一覧＞
      %table{border: "1", class: "table"}
        %tr
          %th
          %th 曲名
          %th バンド名
          %th EASY
          %th NORMAL
          %th HARD
          %th EXPERT
          %th SPECIAL
          %th 配信日
          %th カテゴリ
        - @songs.each do |song|
          %tr
            %td{class: "band#{song.band_id}"}
            %td
              = link_to "#{song.title}", song_path("#{song.id}"), class: "table-title"
            %td.table-band #{song.band.name}
            %td.table-level.easy #{song.easy}
            %td.table-level.normal #{song.normal}
            %td.table-level.hard #{song.hard}
            %td.table-level.expert #{song.expert}
            %td.table-level.special #{song.special}
            %td.table-delivery #{song.delivery}
            %td.table-category{class: "category#{song.category_id}"} #{song.category.name}
  - else
    %table{:border => "1"}
      %tr
        %th 曲名
        %th バンド名
        %th EASY
        %th NORMAL
        %th HARD
        %th EXPERT
        %th SPECIAL
        %th 配信日
        %th カテゴリ
    該当楽曲なし

app/views/songs/show.html.haml
.show
  .show-title
    = @song.title
  .show-band
    演奏バンド：#{@song.band.name}
  .show-delivery
    配信日：#{@song.delivery}
  .show-category
    カテゴリ：#{@song.category.name}
  %h2 楽曲レベル
  .show-level
    .level-box
      .level-box-title.easy
        EASY
      .level-box-value
        = @song.easy
    .level-box
      .level-box-title.normal
        NORMAL
      .level-box-value
        = @song.normal
    .level-box
      .level-box-title.hard
        HARD
      .level-box-value
        = @song.hard
    .level-box
      .level-box-title.expert
        EXPERT
      .level-box-value
        = @song.expert
    - if @song.special
      .level-box
        .level-box-title.special
          SPECIAL
        .level-box-value
          = @song.special